GET http://localhost:3000/contacts

POST http://localhost:3000/contacts/
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "phone": "9876543210",
  "address": "123 Main St"
}
